//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SurvayEvaluation
    {
        public SurvayEvaluation()
        {
            this.SurvayAnswers = new HashSet<SurvayAnswer>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Nationality { get; set; }
        public string TypeOfCar { get; set; }
        public string Telephone { get; set; }
        [DataType(DataType.EmailAddress)]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "Email is not valid")]
        public string Email { get; set; }
        public System.DateTime EvaluationDate { get; set; }
        public Nullable<System.TimeSpan> EvaluationTime { get; set; }
        public Nullable<int> FK_CustomerID { get; set; }
        public string CustomerMobile { get; set; }
    
        public virtual ICollection<SurvayAnswer> SurvayAnswers { get; set; }
    }
}
