//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public int ID { get; set; }
        public string Imagename { get; set; }
        public Nullable<int> AdsOrder { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> Lastmodifieddate { get; set; }
        public Nullable<int> FK_CreatorID { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
    }
}
