//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditing
    {
        public int ID { get; set; }
        public string AuditingNo { get; set; }
        public Nullable<System.DateTime> AuditingDate { get; set; }
        public Nullable<int> Fk_ServiceCenterID { get; set; }
        public Nullable<int> FK_DocStatusID { get; set; }
        public Nullable<int> FK_SysUserID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    }
}
