//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutomatedRequest
    {
        public int ID { get; set; }
        public string AutRequestNo { get; set; }
        public Nullable<int> FK_CenterID { get; set; }
        public Nullable<int> FK_StatusID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> FK_SalesItemID { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> FK_ManagerID { get; set; }
    }
}
