//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingCancelReason
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public Nullable<bool> IsMobilePortal { get; set; }
        public string NameAr { get; set; }
    }
}
