//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int ID { get; set; }
        public Nullable<int> FK_CustomerID { get; set; }
        public string Car_Code { get; set; }
        public Nullable<int> FK_ServiceCenterID { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> FK_CancelReasonID { get; set; }
        public Nullable<bool> IsUserCancel { get; set; }
        public Nullable<int> FK_BookingStatusID { get; set; }
        public string BookingStatus { get; set; }
    }
}
