//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bundle
    {
        public Bundle()
        {
            this.BundleItems = new HashSet<BundleItem>();
            this.POSInvoiceItems = new HashSet<POSInvoiceItem>();
        }
    
        public int ID { get; set; }
        public string BundleName { get; set; }
        public string BundleNameAr { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> BundlePrice { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual ICollection<BundleItem> BundleItems { get; set; }
        public virtual ICollection<POSInvoiceItem> POSInvoiceItems { get; set; }
    }
}
