//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BundleItem
    {
        public int ID { get; set; }
        public Nullable<int> FK_SalesItemID { get; set; }
        public Nullable<decimal> BundleItemPrice { get; set; }
        public Nullable<int> BundleItemQuantity { get; set; }
        public Nullable<int> FK_BundleID { get; set; }
    
        public virtual Bundle Bundle { get; set; }
        public virtual SalesItem SalesItem { get; set; }
    }
}
