//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarBrand
    {
        public CarBrand()
        {
            this.CarModels = new HashSet<CarModel>();
        }
    
        public int ID { get; set; }
        public string BrandName { get; set; }
        public string BrandNameAR { get; set; }
    
        public virtual ICollection<CarModel> CarModels { get; set; }
    }
}
