//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Customers = new HashSet<Customer>();
            this.ServiceCenters = new HashSet<ServiceCenter>();
            this.Areas = new HashSet<Area>();
        }
    
        public int ID { get; set; }
        public string CityName { get; set; }
        public string CityNameAR { get; set; }
        public Nullable<int> FK_RegionIID { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<ServiceCenter> ServiceCenters { get; set; }
        public virtual ICollection<Area> Areas { get; set; }
    }
}
