//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collector
    {
        public Collector()
        {
            this.CollectorsDailyCodes = new HashSet<CollectorsDailyCode>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ColImage { get; set; }
        public string Extension { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual ICollection<CollectorsDailyCode> CollectorsDailyCodes { get; set; }
    }
}
