//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractUser
    {
        public int ID { get; set; }
        public Nullable<int> FK_ContractID { get; set; }
        public Nullable<int> FK_UserID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual User User { get; set; }
    }
}
