//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerNotification
    {
        public int ID { get; set; }
        public int FK_NotificationID { get; set; }
        public int FK_CustomerID { get; set; }
        public bool IsSeen { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual MLPNotification MLPNotification { get; set; }
    }
}
