//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.LoginLogs = new HashSet<LoginLog>();
            this.RedemptionRequests = new HashSet<RedemptionRequest>();
            this.CustomerNotifications = new HashSet<CustomerNotification>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CustomerSCID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> FK_CityID { get; set; }
        public Nullable<int> FK_ServiceCenterID { get; set; }
        public Nullable<int> FK_UserID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.DateTime> ServerLastModifiedDate { get; set; }
        public string CustomerCode { get; set; }
        public string Area { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsMobileUser { get; set; }
        public Nullable<int> FK_LatestLevelID { get; set; }
        public Nullable<int> CurrentPoints { get; set; }
        public bool IsFristlogin { get; set; }
        public Nullable<int> FK_AreaID { get; set; }
        public Nullable<int> NoOfPoints { get; set; }
        public Nullable<System.DateTime> FirstLoginDate { get; set; }
        public string ConfirmationCode { get; set; }
        public string AlfursanNo { get; set; }
    
        public virtual City City { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<LoginLog> LoginLogs { get; set; }
        public virtual ICollection<RedemptionRequest> RedemptionRequests { get; set; }
        public virtual ICollection<CustomerNotification> CustomerNotifications { get; set; }
        public virtual Area Area1 { get; set; }
    }
}
