//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EngineType
    {
        public EngineType()
        {
            this.CustomersCarNumbers = new HashSet<CustomersCarNumber>();
        }
    
        public int Engine_ID { get; set; }
        public string Type_Name { get; set; }
        public string Type_NameAr { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public bool IsMobile { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<CustomersCarNumber> CustomersCarNumbers { get; set; }
    }
}
