//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.Users = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public string LanguageArName { get; set; }
        public string LanguageEnName { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
