//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoyaltyLevel
    {
        public int ID { get; set; }
        public string LevelEng { get; set; }
        public string LevelAR { get; set; }
        public Nullable<int> NoOfVisits { get; set; }
        public Nullable<int> DuePoints { get; set; }
        public Nullable<decimal> PointsPerSAR { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> FK_CreatorID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public Nullable<int> FromPoints { get; set; }
        public Nullable<int> ToPoints { get; set; }
    }
}
