//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public int MenuItemID { get; set; }
        public string MenuItemName { get; set; }
        public string MenuItemDesc { get; set; }
        public string ImageUrl { get; set; }
        public string NavigationUrl { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string MenuItemNameAR { get; set; }
    }
}
