//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageComment
    {
        public int ID { get; set; }
        public string ContactMessage { get; set; }
        public Nullable<System.DateTime> MessageDate { get; set; }
        public string MessageType { get; set; }
        public Nullable<int> FK_SenderID { get; set; }
        public Nullable<int> FK_MessageThreadID { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    }
}
