//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MLPDB01Entities : DbContext
    {
        public MLPDB01Entities()
            : base("name=MLPDB01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminConfiguration> AdminConfigurations { get; set; }
        public virtual DbSet<AdminSetting> AdminSettings { get; set; }
        public virtual DbSet<Auditing> Auditings { get; set; }
        public virtual DbSet<AuditingItem> AuditingItems { get; set; }
        public virtual DbSet<AutomatedRequest> AutomatedRequests { get; set; }
        public virtual DbSet<Award> Awards { get; set; }
        public virtual DbSet<BookingService> BookingServices { get; set; }
        public virtual DbSet<BookingTimeSlot> BookingTimeSlots { get; set; }
        public virtual DbSet<Bundle> Bundles { get; set; }
        public virtual DbSet<BundleItem> BundleItems { get; set; }
        public virtual DbSet<Category1> Category1 { get; set; }
        public virtual DbSet<Category2> Category2 { get; set; }
        public virtual DbSet<Category3> Category3 { get; set; }
        public virtual DbSet<Category4> Category4 { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Collection> Collections { get; set; }
        public virtual DbSet<Collector> Collectors { get; set; }
        public virtual DbSet<CollectorsDailyCode> CollectorsDailyCodes { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomersCarNumber> CustomersCarNumbers { get; set; }
        public virtual DbSet<DailyReportsLog> DailyReportsLogs { get; set; }
        public virtual DbSet<DashBoardChart> DashBoardCharts { get; set; }
        public virtual DbSet<DocStatu> DocStatus { get; set; }
        public virtual DbSet<InvoicePayment> InvoicePayments { get; set; }
        public virtual DbSet<InvoiceType> InvoiceTypes { get; set; }
        public virtual DbSet<ItemType> ItemTypes { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<LoginLog> LoginLogs { get; set; }
        public virtual DbSet<LoyaltyLevel> LoyaltyLevels { get; set; }
        public virtual DbSet<MenuItem> MenuItems { get; set; }
        public virtual DbSet<MenuSubMenuItem> MenuSubMenuItems { get; set; }
        public virtual DbSet<MessageComment> MessageComments { get; set; }
        public virtual DbSet<MessageThread> MessageThreads { get; set; }
        public virtual DbSet<MobileCategory> MobileCategories { get; set; }
        public virtual DbSet<MobileDailyReport> MobileDailyReports { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NotificationMessage> NotificationMessages { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<NotificationsStatu> NotificationsStatus { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<Point> Points { get; set; }
        public virtual DbSet<PointsReason> PointsReasons { get; set; }
        public virtual DbSet<PointsReasonsProduct> PointsReasonsProducts { get; set; }
        public virtual DbSet<PointsReasonsSCenter> PointsReasonsSCenters { get; set; }
        public virtual DbSet<POSConnectionLog> POSConnectionLogs { get; set; }
        public virtual DbSet<POSInvoice> POSInvoices { get; set; }
        public virtual DbSet<POSInvoiceItem> POSInvoiceItems { get; set; }
        public virtual DbSet<PosReport> PosReports { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<Reason> Reasons { get; set; }
        public virtual DbSet<RedemptionRequest> RedemptionRequests { get; set; }
        public virtual DbSet<RedemptionStatu> RedemptionStatus { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<RequestItem> RequestItems { get; set; }
        public virtual DbSet<RequestOrder> RequestOrders { get; set; }
        public virtual DbSet<RequestsLog> RequestsLogs { get; set; }
        public virtual DbSet<RequestStatu> RequestStatus { get; set; }
        public virtual DbSet<RequestType> RequestTypes { get; set; }
        public virtual DbSet<ReturnInvoice> ReturnInvoices { get; set; }
        public virtual DbSet<ReturnInvoiceItem> ReturnInvoiceItems { get; set; }
        public virtual DbSet<RptGroup> RptGroups { get; set; }
        public virtual DbSet<SafeLog> SafeLogs { get; set; }
        public virtual DbSet<SalesItem> SalesItems { get; set; }
        public virtual DbSet<SalesItemCategory> SalesItemCategories { get; set; }
        public virtual DbSet<ServiceCenterInventory> ServiceCenterInventories { get; set; }
        public virtual DbSet<ServiceCenterSalesItem> ServiceCenterSalesItems { get; set; }
        public virtual DbSet<SubMenuItem> SubMenuItems { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Suppliment> Suppliments { get; set; }
        public virtual DbSet<SupplimentItem> SupplimentItems { get; set; }
        public virtual DbSet<SupplimentStatu> SupplimentStatus { get; set; }
        public virtual DbSet<SupplyNotification> SupplyNotifications { get; set; }
        public virtual DbSet<SupplyNotificationAction> SupplyNotificationActions { get; set; }
        public virtual DbSet<SupplyOrder> SupplyOrders { get; set; }
        public virtual DbSet<SupplyOrderItem> SupplyOrderItems { get; set; }
        public virtual DbSet<SystemUser> SystemUsers { get; set; }
        public virtual DbSet<TempCustomer> TempCustomers { get; set; }
        public virtual DbSet<TimeSlot> TimeSlots { get; set; }
        public virtual DbSet<TransferItem> TransferItems { get; set; }
        public virtual DbSet<Transfer> Transfers { get; set; }
        public virtual DbSet<TransferStatu> TransferStatus { get; set; }
        public virtual DbSet<TransferType> TransferTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserGroupsPage> UserGroupsPages { get; set; }
        public virtual DbSet<UserServiceCenter> UserServiceCenters { get; set; }
        public virtual DbSet<UsersGroup> UsersGroups { get; set; }
        public virtual DbSet<UsersLog> UsersLogs { get; set; }
        public virtual DbSet<BookingCancelReason> BookingCancelReasons { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<CustomerNotification> CustomerNotifications { get; set; }
        public virtual DbSet<MLPNotification> MLPNotifications { get; set; }
        public virtual DbSet<MLPNotificationType> MLPNotificationTypes { get; set; }
        public virtual DbSet<BookingStatu> BookingStatus { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<ServiceCenter> ServiceCenters { get; set; }
        public virtual DbSet<MLPCustomerToken> MLPCustomerTokens { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<CarBrand> CarBrands { get; set; }
        public virtual DbSet<CarModel> CarModels { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<ContractCar> ContractCars { get; set; }
        public virtual DbSet<ContractPriceList> ContractPriceLists { get; set; }
        public virtual DbSet<ContractUser> ContractUsers { get; set; }
        public virtual DbSet<EngineType> EngineTypes { get; set; }
        public virtual DbSet<MLPSMSConfirmation> MLPSMSConfirmations { get; set; }
        public virtual DbSet<CustomersClearNotification> CustomersClearNotifications { get; set; }
        public virtual DbSet<SurvayAnswer> SurvayAnswers { get; set; }
        public virtual DbSet<SurvayEvaluation> SurvayEvaluations { get; set; }
        public virtual DbSet<SurvayQuestion> SurvayQuestions { get; set; }
        public virtual DbSet<SurvayMultiChoose> SurvayMultiChooses { get; set; }
        public virtual DbSet<Advertisement> Advertisements { get; set; }
        public virtual DbSet<AlForsanRedemption> AlForsanRedemptions { get; set; }
        public virtual DbSet<AwardsType> AwardsTypes { get; set; }
    }
}
