//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLPNotification
    {
        public MLPNotification()
        {
            this.CustomerNotifications = new HashSet<CustomerNotification>();
        }
    
        public int ID { get; set; }
        public string NotificationMessage { get; set; }
        public Nullable<System.DateTime> NotificationDate { get; set; }
        public string NotificationView { get; set; }
        public int FK_NotificationTypeID { get; set; }
        public Nullable<int> CreatorID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<CustomerNotification> CustomerNotifications { get; set; }
        public virtual MLPNotificationType MLPNotificationType { get; set; }
    }
}
