//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLPSMSConfirmation
    {
        public int ID { get; set; }
        public string CustomerMobile { get; set; }
        public Nullable<bool> FirstLoginMS { get; set; }
        public Nullable<bool> MobilOilMS { get; set; }
        public Nullable<bool> UpLevelMS { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastModificationDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
