//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int ID { get; set; }
        public Nullable<int> FK_Message { get; set; }
        public Nullable<int> FK_CenterID { get; set; }
        public Nullable<int> FK_UserID { get; set; }
        public Nullable<int> FK_Status { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual NotificationMessage NotificationMessage { get; set; }
        public virtual NotificationsStatu NotificationsStatu { get; set; }
        public virtual User User { get; set; }
        public virtual ServiceCenter ServiceCenter { get; set; }
    }
}
