//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationMessage
    {
        public NotificationMessage()
        {
            this.Notifications = new HashSet<Notification>();
        }
    
        public int ID { get; set; }
        public string Message { get; set; }
    
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
