//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentType
    {
        public string ID { get; set; }
        public string PaymentTypeName { get; set; }
        public string PaymentTypeNameAr { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    }
}
