//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointsReason
    {
        public PointsReason()
        {
            this.PointsReasonsProducts = new HashSet<PointsReasonsProduct>();
            this.PointsReasonsSCenters = new HashSet<PointsReasonsSCenter>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FK_ReasonID { get; set; }
        public Nullable<int> NoOfPoints { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsOnce { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual Reason Reason { get; set; }
        public virtual ICollection<PointsReasonsProduct> PointsReasonsProducts { get; set; }
        public virtual ICollection<PointsReasonsSCenter> PointsReasonsSCenters { get; set; }
    }
}
