//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSConnectionLog
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> LogTimeStamp { get; set; }
        public Nullable<int> FK_UserID { get; set; }
        public string SourceIP { get; set; }
        public string Token { get; set; }
        public string LogType { get; set; }
        public string Description { get; set; }
    
        public virtual User User { get; set; }
    }
}
