//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSInvoiceItem
    {
        public POSInvoiceItem()
        {
            this.POSInvoiceItem1 = new HashSet<POSInvoiceItem>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FK_SalesItemID { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> OriginalPrice { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> FK_InvoiceID { get; set; }
        public Nullable<int> FK_BundleID { get; set; }
        public Nullable<int> FK_ParentID { get; set; }
        public Nullable<int> LoyaltyPoints { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Bundle Bundle { get; set; }
        public virtual POSInvoice POSInvoice { get; set; }
        public virtual ICollection<POSInvoiceItem> POSInvoiceItem1 { get; set; }
        public virtual POSInvoiceItem POSInvoiceItem2 { get; set; }
        public virtual SalesItem SalesItem { get; set; }
    }
}
