//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSInvoice
    {
        public POSInvoice()
        {
            this.POSInvoiceItems = new HashSet<POSInvoiceItem>();
        }
    
        public int ID { get; set; }
        public string FK_CustomerCode { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string PaymentType { get; set; }
        public Nullable<int> FK_ServiceCenterID { get; set; }
        public Nullable<int> FK_UserID { get; set; }
        public Nullable<int> VisaLastDigits { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.DateTime> ServerLastModifiedDate { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public string CarNumber { get; set; }
        public string InvoiceNo { get; set; }
        public string FK_CarCode { get; set; }
        public string CurrentMileage { get; set; }
        public string NextVisit { get; set; }
        public Nullable<int> LoyaltyPoints { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> VatPercent { get; set; }
        public Nullable<decimal> TotalWithVat { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<POSInvoiceItem> POSInvoiceItems { get; set; }
    }
}
