//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedemptionRequest
    {
        public RedemptionRequest()
        {
            this.AlForsanRedemptions = new HashSet<AlForsanRedemption>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FK_CustomerID { get; set; }
        public Nullable<int> FK_AwardID { get; set; }
        public Nullable<int> FK_ServiceCenterID { get; set; }
        public Nullable<System.DateTime> RedeemDate { get; set; }
        public Nullable<int> RedeemPoints { get; set; }
        public string CustomerConfirmCode { get; set; }
        public string RedemptionConfirmCode { get; set; }
        public Nullable<int> POSCreatorCodeID { get; set; }
        public Nullable<int> FK_RedeemStatusID { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual Award Award { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual RedemptionStatu RedemptionStatu { get; set; }
        public virtual ServiceCenter ServiceCenter { get; set; }
        public virtual ICollection<AlForsanRedemption> AlForsanRedemptions { get; set; }
    }
}
