//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestsLog
    {
        public int ID { get; set; }
        public int FK_ServiceCenterID { get; set; }
        public Nullable<int> FK_ItemID { get; set; }
        public Nullable<int> FK_UserID { get; set; }
        public string ActionType { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string FK_RequestNo { get; set; }
    }
}
