//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnInvoice
    {
        public int ID { get; set; }
        public string FK_InvoiceNo { get; set; }
        public string ReturnInvoiceNo { get; set; }
        public Nullable<decimal> TotalRetAmount { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string PaymentType { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> FK_UserID { get; set; }
    }
}
