//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnInvoiceItem
    {
        public int ID { get; set; }
        public Nullable<int> FK_SalesItemID { get; set; }
        public Nullable<int> ReturnQty { get; set; }
        public Nullable<decimal> OriginalPrice { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> FK_RetInvoiceID { get; set; }
        public Nullable<int> FK_BundleID { get; set; }
        public Nullable<int> FK_ParentID { get; set; }
    }
}
