//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCenterSalesItem
    {
        public int ID { get; set; }
        public Nullable<int> FK_ItemID { get; set; }
        public Nullable<int> Threshold { get; set; }
        public Nullable<int> FK_ServiceCenterID { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> MaxThreshold { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual SalesItem SalesItem { get; set; }
    }
}
