//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCenter
    {
        public ServiceCenter()
        {
            this.Notifications = new HashSet<Notification>();
            this.PointsReasonsSCenters = new HashSet<PointsReasonsSCenter>();
            this.RedemptionRequests = new HashSet<RedemptionRequest>();
            this.SupplyNotifications = new HashSet<SupplyNotification>();
        }
    
        public int ID { get; set; }
        public string CenterName { get; set; }
        public string CenterNameAr { get; set; }
        public string Address { get; set; }
        public string AddressAR { get; set; }
        public Nullable<int> FK_CityID { get; set; }
        public string AreaAr { get; set; }
        public string Area { get; set; }
        public Nullable<decimal> px { get; set; }
        public Nullable<decimal> py { get; set; }
        public string POSImage { get; set; }
        public string DescriptionHTML { get; set; }
        public string CenterGroup { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<decimal> RemainingValue { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<bool> IsCost { get; set; }
        public Nullable<System.DateTime> LicenseExpiryDate { get; set; }
        public Nullable<System.DateTime> SCExpiryDate { get; set; }
        public string MapLink { get; set; }
        public Nullable<System.TimeSpan> OpeningTime { get; set; }
        public Nullable<System.TimeSpan> ClosingTime { get; set; }
        public Nullable<int> NoOfServicesPerTimeSlot { get; set; }
        public Nullable<int> NoOfShifts { get; set; }
        public string ContactNo { get; set; }
        public bool IsInLoyaltyProgram { get; set; }
        public string DescriptionHTMLAR { get; set; }
        public Nullable<bool> IsBooking { get; set; }
        public string Email { get; set; }
        public System.DateTime OpenningDate { get; set; }
        public Nullable<int> TerritoryId { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<PointsReasonsSCenter> PointsReasonsSCenters { get; set; }
        public virtual ICollection<RedemptionRequest> RedemptionRequests { get; set; }
        public virtual ICollection<SupplyNotification> SupplyNotifications { get; set; }
    }
}
