//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubMenuItem
    {
        public int SubMenuItemID { get; set; }
        public string SubMenuItemName { get; set; }
        public string SubMenuItemUrl { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string SubMenuItemNameAR { get; set; }
    }
}
