//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyOrder
    {
        public SupplyOrder()
        {
            this.SupplyOrderItems = new HashSet<SupplyOrderItem>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FK_ServiceCenterID { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> ServerLastModifiedDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string FK_RequestNo { get; set; }
        public string FK_AutReqestNo { get; set; }
        public Nullable<int> FK_UserID { get; set; }
        public string FK_TransferNo { get; set; }
        public string FK_SupplimentNo { get; set; }
    
        public virtual ICollection<SupplyOrderItem> SupplyOrderItems { get; set; }
    }
}
