//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyNotificationAction
    {
        public int ID { get; set; }
        public string ActionMessage { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public Nullable<int> FK_UserID { get; set; }
        public Nullable<int> FK_SupplyNotificationID { get; set; }
    
        public virtual SupplyNotification SupplyNotification { get; set; }
        public virtual User User { get; set; }
    }
}
