//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurvayAnswer
    {
        public int ID { get; set; }
        public Nullable<int> FK_EvaluaionID { get; set; }
        public Nullable<int> FK_QuestionID { get; set; }
        public Nullable<int> AnswerValue { get; set; }
        public string AnswerTxtValue { get; set; }
        public System.DateTime AnswerDate { get; set; }
        public string Comments { get; set; }
    
        public virtual SurvayQuestion SurvayQuestion { get; set; }
        public virtual SurvayEvaluation SurvayEvaluation { get; set; }
    }
}
